// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fibCppWrap
Rcpp::NumericVector fibCppWrap(Rcpp::NumericVector n_);
RcppExport SEXP rcpptime_fibCppWrap(SEXP n_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type n_(n_SEXP);
    rcpp_result_gen = Rcpp::wrap(fibCppWrap(n_));
    return rcpp_result_gen;
END_RCPP
}
// cppPisumWrap
Rcpp::NumericVector cppPisumWrap(Rcpp::NumericVector lim_);
RcppExport SEXP rcpptime_cppPisumWrap(SEXP lim_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lim_(lim_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppPisumWrap(lim_));
    return rcpp_result_gen;
END_RCPP
}
// sumCppWrap
Rcpp::NumericVector sumCppWrap(Rcpp::NumericVector n_);
RcppExport SEXP rcpptime_sumCppWrap(SEXP n_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type n_(n_SEXP);
    rcpp_result_gen = Rcpp::wrap(sumCppWrap(n_));
    return rcpp_result_gen;
END_RCPP
}
