# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fibCppWrap <- function(n_) {
    .Call('rcpptime_fibCppWrap', PACKAGE = 'rcpptime', n_)
}

cppPisumWrap <- function(lim_) {
    .Call('rcpptime_cppPisumWrap', PACKAGE = 'rcpptime', lim_)
}

sumCppWrap <- function(n_) {
    .Call('rcpptime_sumCppWrap', PACKAGE = 'rcpptime', n_)
}

